redwood_web_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: RedwoodWebBundle:Default:index }

register:
    pattern:  /register
    defaults: { _controller: RedwoodWebBundle:Register:index }