redwood_web_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: RedwoodWebBundle:Default:index }

register:
    pattern:  /register
    defaults: { _controller: RedwoodWebBundle:Register:index }

login:
    pattern:  /login
    defaults: { _controller: RedwoodWebBundle:Login:index }

login_check:
    pattern:  /login_check