homepage:
    pattern:  /hello
    defaults: { _controller: RedwoodWebBundle:Default:index }

register:
    pattern:  /register
    defaults: { _controller: RedwoodWebBundle:Register:index }

login:
    pattern:  /login
    defaults: { _controller: RedwoodWebBundle:Login:index }

login_check:
    pattern:  /login_check

register_success:
    pattern:  /register/success/{id}/{hash}
    defaults: { _controller:  RedwoodWebBundle:Register:success }

register_email_verify:
    pattern:  /register/email/verify/{token}
    defaults: { _controller: RedwoodWebBundle:Register:emailVerify }